# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0002_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='marker',
            name='radius',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='x',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='y',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
